id: I82BAE344
ocr_import_info:
  timestamp: '2023-06-18T10:53:01.819482+00:00'
  batch_id: batch-c9a2
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Peche job
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-18 14:39:53.304120+00:00
last_modified: 2023-06-18 14:39:53.304128+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22731
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22731
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེས་བྱ་ཀུན་ཁྱབ།
  languages:
  - bo
  author: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.9960692743302237
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN22907:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22907
      total_pages: 742
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN22907.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9961116075981137
  I3CN22905:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22905
      total_pages: 629
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN22905.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9958504052345626
  I3CN22906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22906
      total_pages: 794
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN22906.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9962020496553234
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
